# Generated by Django 3.0.6 on 2025-02-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('I_MatriculaID', models.AutoField(primary_key=True, serialize=False)),
                ('D_FechaMatricula', models.DateField()),
                ('D_DateInsert', models.DateField()),
                ('D_DateUpDate', models.DateField()),
                ('I_UsuarioID', models.IntegerField()),
                ('I_ProgramacionID', models.ForeignKey(db_column='I_ProgramacionID', on_delete=django.db.models.deletion.CASCADE, to='TR.Programacion')),
                ('N_CodEstudianteID', models.ForeignKey(db_column='N_CodEstudianteID', on_delete=django.db.models.deletion.CASCADE, to='TR.Estudiante')),
            ],
        ),
    ]
