# Generated by Django 3.0.6 on 2025-02-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='I_Identificador',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
