# Generated by Django 3.0.6 on 2025-03-12 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TI', '0002_matricula_i_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='D_DateInsert',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='D_DateUpDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='D_FechaMatricula',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
