# Generated by Django 3.0.6 on 2025-03-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TI', '0003_auto_20250312_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='D_DateInsert',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='D_DateUpDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='D_FechaMatricula',
            field=models.DateField(),
        ),
    ]
