# Generated by Django 3.0.6 on 2025-03-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TI', '0004_auto_20250312_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='D_FechaMatricula',
            field=models.DateTimeField(),
        ),
    ]
