# Generated by Django 3.0.6 on 2025-02-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('I_AsignaturaID', models.AutoField(primary_key=True, serialize=False)),
                ('I_CodAsignatura', models.IntegerField()),
                ('T_NombreAsignatura', models.CharField(max_length=250)),
                ('T_Ciclo', models.CharField(max_length=4)),
                ('I_Creditos', models.IntegerField()),
                ('D_DateInsert', models.DateField()),
                ('D_DateUpDate', models.DateField()),
                ('I_UsuarioID', models.IntegerField()),
                ('I_CondicionAsignaturaID', models.ForeignKey(db_column='I_CondicionAsignaturaID', on_delete=django.db.models.deletion.CASCADE, to='TC.CondicionAsignaturas')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('N_CodDocenteID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('N_DniDocente', models.CharField(max_length=8)),
                ('T_ApelPaterno', models.CharField(max_length=50)),
                ('T_ApelMaterno', models.CharField(max_length=50)),
                ('T_Nombre', models.CharField(max_length=50)),
                ('D_DateInsert', models.DateField()),
                ('D_DateUpDate', models.DateField()),
                ('I_UsuarioID', models.IntegerField()),
                ('I_DepAcademicoID', models.ForeignKey(db_column='I_DepAcademicoID', on_delete=django.db.models.deletion.CASCADE, to='TC.DepartamentoAcademicos')),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('I_EscuelaID', models.AutoField(primary_key=True, serialize=False)),
                ('T_NombreEscuela', models.CharField(max_length=100)),
                ('I_FacultadID', models.ForeignKey(db_column='I_FacultadID', on_delete=django.db.models.deletion.CASCADE, to='TC.Facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('I_EspecialidadID', models.AutoField(primary_key=True, serialize=False)),
                ('T_NombreEspecialidad', models.CharField(max_length=100)),
                ('I_EscuelaID', models.ForeignKey(db_column='I_EscuelaID', on_delete=django.db.models.deletion.CASCADE, to='TR.Escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('N_CodEstudianteID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('N_DniEstudiante', models.CharField(max_length=10)),
                ('I_AnioIngreso', models.IntegerField()),
                ('I_UltiSemestreCursado', models.IntegerField()),
                ('I_PromPonderado', models.IntegerField()),
                ('T_ApelPaterno', models.CharField(max_length=50)),
                ('T_ApelMaterno', models.CharField(max_length=50)),
                ('T_Nombre', models.CharField(max_length=50)),
                ('B_CondicionEstudiante', models.BooleanField()),
                ('D_DateInsert', models.DateField()),
                ('D_DateUpDate', models.DateField()),
                ('I_UsuarioID', models.IntegerField()),
                ('T_Email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('I_UsuarioID', models.AutoField(primary_key=True, serialize=False)),
                ('T_NombreUsuario', models.CharField(max_length=50)),
                ('T_Contrasenia', models.CharField(max_length=500)),
                ('T_ApelPaterno', models.CharField(max_length=50)),
                ('T_ApelMaterno', models.CharField(max_length=50)),
                ('T_Nombre', models.CharField(max_length=50)),
                ('B_Habilitado', models.BooleanField()),
                ('D_DateInsert', models.DateField()),
                ('D_DateUpDate', models.DateField()),
                ('I_UsuarioID_1', models.IntegerField()),
                ('I_RolID', models.ForeignKey(db_column='I_RolID', on_delete=django.db.models.deletion.CASCADE, to='TC.UsuarioRoles')),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('I_ProgramacionID', models.AutoField(primary_key=True, serialize=False)),
                ('C_Periodo', models.CharField(max_length=2)),
                ('C_Turno', models.CharField(max_length=2)),
                ('C_Seccion', models.CharField(max_length=2)),
                ('D_HoraInicio1', models.TimeField(blank=True, null=True)),
                ('D_HoraFin1', models.TimeField(blank=True, null=True)),
                ('D_HoraInicio2', models.TimeField(blank=True, null=True)),
                ('D_HoraFin2', models.TimeField(blank=True, null=True)),
                ('D_HoraInicio3', models.TimeField(blank=True, null=True)),
                ('D_HoraFin3', models.TimeField(blank=True, null=True)),
                ('T_Aula', models.CharField(max_length=10)),
                ('I_Cupos', models.IntegerField()),
                ('D_DateInsert', models.DateField()),
                ('D_DateUpDate', models.DateField()),
                ('I_UsuarioID', models.IntegerField()),
                ('I_AsignaturaID', models.ForeignKey(db_column='I_AsignaturaID', on_delete=django.db.models.deletion.CASCADE, to='TR.Asignatura')),
                ('I_DiaID1', models.ForeignKey(blank=True, db_column='I_DiaID1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programacion_i_dia1', to='TC.Dia')),
                ('I_DiaID2', models.ForeignKey(blank=True, db_column='I_DiaID2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programacion_d_dia2', to='TC.Dia')),
                ('I_DiaID3', models.ForeignKey(blank=True, db_column='I_DiaID3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programacion_d_dia3', to='TC.Dia')),
                ('N_CodDocenteID', models.ForeignKey(db_column='N_CodDocenteID', on_delete=django.db.models.deletion.CASCADE, to='TR.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCurriculares',
            fields=[
                ('I_PlanID', models.AutoField(primary_key=True, serialize=False)),
                ('I_AnioPlan', models.IntegerField()),
                ('D_DateInsert', models.DateField()),
                ('D_DateUpDate', models.DateField()),
                ('I_UsuarioID', models.IntegerField()),
                ('I_EspecialidadID', models.ForeignKey(db_column='I_EspecialidadID', on_delete=django.db.models.deletion.CASCADE, to='TR.Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('I_ComprobanteID', models.AutoField(primary_key=True, serialize=False)),
                ('T_CodLiquidacion', models.CharField(max_length=20)),
                ('B_CondicionPago', models.BooleanField()),
                ('D_FechaPago', models.DateField()),
                ('D_DateInsert', models.DateField()),
                ('D_DateUpDate', models.DateField()),
                ('I_UsuarioID', models.IntegerField()),
                ('I_EntidadID', models.ForeignKey(db_column='I_EntidadID', on_delete=django.db.models.deletion.CASCADE, to='TC.EntidadRecaudadoras')),
                ('N_CodEstudianteID', models.ForeignKey(db_column='N_CodEstudianteID', on_delete=django.db.models.deletion.CASCADE, to='TR.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('N_CodOperadorID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('N_DniOperador', models.CharField(max_length=10)),
                ('T_ApelPaterno', models.CharField(max_length=50)),
                ('T_ApelMaterno', models.CharField(max_length=50)),
                ('T_Nombre', models.CharField(max_length=70)),
                ('D_DateInsert', models.DateField()),
                ('D_DateUpDate', models.DateField()),
                ('I_UsuarioID', models.IntegerField()),
                ('T_Email', models.CharField(max_length=50)),
                ('I_EspecialidadID', models.ForeignKey(db_column='I_EspecialidadID', on_delete=django.db.models.deletion.CASCADE, to='TR.Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAcademicos',
            fields=[
                ('I_HistorialID', models.AutoField(primary_key=True, serialize=False)),
                ('I_AsignaturaID', models.IntegerField()),
                ('B_AsignaturaAprobada', models.BooleanField()),
                ('I_VezLlevadoAsignatura', models.IntegerField()),
                ('D_DateInsert', models.DateField()),
                ('D_DateUpDate', models.DateField()),
                ('I_UsuarioID', models.IntegerField()),
                ('N_CodEstudianteID', models.ForeignKey(db_column='N_CodEstudianteID', on_delete=django.db.models.deletion.CASCADE, to='TR.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='I_PlanID',
            field=models.ForeignKey(db_column='I_PlanID', on_delete=django.db.models.deletion.CASCADE, to='TR.PlanCurriculares'),
        ),
        migrations.CreateModel(
            name='AsignaturaPreRequisitos',
            fields=[
                ('I_AsignaturaPreRequisitoID', models.AutoField(primary_key=True, serialize=False)),
                ('D_DateInsert', models.DateField()),
                ('D_DateUpDate', models.DateField()),
                ('I_UsuarioID', models.IntegerField()),
                ('I_AsignaturaID', models.ForeignKey(db_column='I_AsignaturaID', on_delete=django.db.models.deletion.CASCADE, related_name='asignatura_principal', to='TR.Asignatura')),
                ('I_PreRequisitoID', models.ForeignKey(db_column='I_PreRequisitoID', on_delete=django.db.models.deletion.CASCADE, related_name='asignatura_prerrequisito', to='TR.Asignatura')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='I_PlanID',
            field=models.ForeignKey(db_column='I_PlanID', on_delete=django.db.models.deletion.CASCADE, to='TR.PlanCurriculares'),
        ),
        migrations.CreateModel(
            name='AccesoMatriculas',
            fields=[
                ('I_AccesoID', models.AutoField(primary_key=True, serialize=False)),
                ('D_HoraApertura', models.TimeField()),
                ('D_DiaApertura', models.DateField()),
                ('D_DiaCierre', models.DateField()),
                ('D_HoraCierre', models.TimeField()),
                ('D_DateInsert', models.DateField()),
                ('D_DateUpDate', models.DateField()),
                ('I_UsuarioID', models.IntegerField()),
                ('N_CodOperadorID', models.ForeignKey(db_column='N_CodOperadorID', on_delete=django.db.models.deletion.CASCADE, to='TR.Operador')),
            ],
        ),
    ]
