# Generated by Django 3.0.6 on 2025-02-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TR', '0002_accesomatriculas_t_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='B_QuintoSuperior',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesomatriculas',
            name='T_Categoria',
            field=models.CharField(choices=[('quinto_superior', 'QUINTO SUPERIOR'), ('regulares', 'REGULARES'), ('rezagados', 'REZAGADOS')], max_length=20),
        ),
    ]
