# Generated by Django 3.0.6 on 2025-02-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TR', '0004_auto_20250210_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='B_Habilitado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
