# Generated by Django 3.0.6 on 2025-02-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TR', '0005_programacion_b_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='I_CuposFijos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
