# Generated by Django 3.0.6 on 2025-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TR', '0006_programacion_i_cuposfijos'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='I_Nivel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
