# Generated by Django 3.0.6 on 2025-02-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TR', '0007_estudiante_i_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='I_PromPonderado',
            field=models.FloatField(),
        ),
    ]
