# Generated by Django 3.0.6 on 2025-03-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TR', '0008_auto_20250228_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesomatriculas',
            name='T_Categoria',
            field=models.CharField(choices=[('quinto_superior', 'QUINTO SUPERIOR'), ('regulares_invictos', 'REGULARES INVICTOS'), ('todos', 'TODOS')], max_length=20),
        ),
    ]
